default: &default
  adapter: postgresql
  encoding: unicode
  username: denis
  password: denis
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: Ball_development


test:
  <<: *default
  database: Ball_test

production:
  <<: *default
  database: Ball_production
