default: &default
  adapter: postgresql
  encoding: unicode
  username: hhzzxdtoxaaqgq
  password: vuAbocPf0JxEmFctcKhY--AF_9
  host: ec2-54-163-245-162.compute-1.amazonaws.com
  port: 5432
  pool: 5

development:
  <<: *default
  database: d4ka9run95jj69


test:
  <<: *default
  database: d4ka9run95jj69

production:
  <<: *default
  database: d4ka9run95jj69
